import amazonasIcon from "./amazonas (3).png";
import ballenaIcon from "./ballena (2).png";
import montañasIcon from "./montanas (1).png";
import foodIcon from "./noun_Food_2688587-1.svg";
import sendIcon from "./Path 2282.svg";
import sleepIcon from "./noun_sleeping_947849.svg";
import boteIcon from "./Path 2388.svg";
import avionIcon from "./noun_Plane_2797956.svg";
import reciclarIcon from "./reciclar.png";
import viajeroIcon from "./viajero.png";
import viajero2Icon from "./viajero (1).png";
import wonderOrangeIcon from "./Group 1101.svg";
import wonderBlackIcon from "./Group 1098.svg";
import tucanIcon from "./tucan.png";
import puestaDeSolIcon from "./puesta-de-sol.png";
import PersonAdventureIcon from "./noun_adventure_68979.svg";
import footerImage from "./footer_image.png";
import acoturImage from "./ACOTUR LOGO AI-01.png";
export const amazonas = amazonasIcon;
export const ballena = ballenaIcon;
export const montañas = montañasIcon;
export const food = foodIcon;
export const send = sendIcon;
export const sleep = sleepIcon;
export const bote = boteIcon;
export const avion = avionIcon;
export const reciclar = reciclarIcon;
export const viajero1 = viajeroIcon;
export const viajero2 = viajero2Icon;
export const wonderOrange = wonderOrangeIcon;
export const wonderBlack = wonderBlackIcon;
export const tucan = tucanIcon;
export const puestaDelSol = puestaDeSolIcon;
export const PersonAdventure = PersonAdventureIcon;
export const footer = footerImage;
export const acotur = acoturImage;
